server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    leaseRenewalIntervalInSeconds: 3
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    renewalPercentThreshold: 0.32
    waitTimeInMsWhenSyncEmpty: 0
